version: '2'

networks:
  default-network:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: deployment/local/images/app/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    container_name: google_one_tap_example_app
    networks:
      - default-network